# Generated by Django 2.1.7 on 2019-05-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('planetRadius', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=5, max_digits=7)),
                ('color', models.CharField(choices=[('0x555555', 'first'), ('0x7658ef', 'second'), ('0x1EF9F8', 'third')], default='0x555555', max_length=15)),
                ('vector', models.IntegerField(choices=[(1, 'Clockwise'), (-1, 'Counter clockwise')], default=1)),
                ('orbitRadius', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('planetNumber', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='solarSystem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solar.SolarSystem'),
        ),
    ]
